[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]


[build]
target = "x86-unknown-bare_metal.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"